### PR TITLE
Terraform script for vision service architecture

### PR DESCRIPTION
**Pull request by carlgira-oracle**
Hi, just adding all files of the terraform script.

Thanks

### CODE REVIEW

**Comment by carlgira-oracle** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by carlgira** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by carlgira** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by ttscoff — APPROVED** [review]

**Comment by ttscoff** [comment]
FYI, I'm reviewing/approving this PR, but reviews should normally be done using the buddy system, not by me.

**Pull request merged**
